[project]
name = "assignment-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "eralchemy>=1.5.0",
    "eralchemy2>=1.4.1",
    "ipynb>=0.5.1",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
]
